version: '3.8'
services:
  ##############Spring-Boot Application Docker-Compose Configuration##############
  mongodb-dockerize: #This will be the name of the container
    image: mongodb-dockerize # Name of the Image
    ports:
      - 8080:8080
    depends_on:
      - mongodb
    environment:
#      - SERVER_PORT=8000
#      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_DATA_MONGODB_AUTHENTICATION_DATABASE=admin
#      - SPRING_DATA_MONGODB_AUTO_INDEX_CREATION=true
      - SPRING_DATA_MONGODB_HOST=mongodb
      - SPRING_DATA_MONGODB_PORT=27017
      - SPRING_DATA_MONGODB_USERNAME=admin
      - SPRING_DATA_MONGODB_PASSWORD=password
      - SPRING_DATA_MONGODB_DATABASE=MyDatabase

  ##############Mongo Database Docker-Compose Configuration##############
  mongodb:  #This will be the name of the container
    image: mongo # Name of the Image
    container_name: mongodb
    restart: unless-stopped
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
      - MONGO_INITDB_DATABASE=MyDatabase
      - MONGO_DB_USERNAME=admin
      - MONGO_DB_PASSWORD=password
    volumes:
      - mongo-data:/data/db

  ##############Mongo-Express Docker-Compose Configuration##############
  mongo-express:  #This will be the name of the container
    image: mongo-express # Name of the Image
    ports:
      - 8081:8081
    depends_on:
      - mongodb
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=password
      - ME_CONFIG_MONGODB_SERVER=mongodb
volumes:
  mongo-data:
    driver: local